apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: list-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: list-service-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URL
      remoteRef:
        key: shared-pg
        property: POSTGRES_URL