apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: email-service-secret
    creationPolicy: Owner
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: email-service
        property: SMTP_HOST
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: email-service
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: email-service
        property: SMTP_PASSWORD
    - secretKey: FROM_EMAIL
      remoteRef:
        key: email-service
        property: FROM_EMAIL