apiVersion: v1
kind: Service
metadata:
  name: parrot
  namespace: eks-blue-green
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: parrot
    version: ${LABEL_VERSION}
  type: LoadBalancer