apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: email-service
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: email-service
      previewService: email-service-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${SERVICE}:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: email-service-secret
      imagePullSecrets:
      - name: regcred