name: ECR Setup

on:
  workflow_dispatch:

jobs:
  ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd infra/00-ecr-setup
        terraform init -input=false
      continue-on-error: false

    - name: Terraform Validate
      run: |
        cd infra/00-ecr-setup
        terraform validate
      continue-on-error: false

    - name: Terraform Plan
      run: |
        cd infra/00-ecr-setup
        terraform plan -out=tfplan
      continue-on-error: false

    - name: Terraform Apply (ECR)
      run: |
        cd infra/00-ecr-setup
        terraform apply -input=false -auto-approve tfplan
      continue-on-error: false
