name: ECR Setup

on:
  workflow_dispatch:

jobs:
  ecr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-west-2

    - name: Who am I?
      run: aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd infra/00-ecr-setup
        terraform init -input=false

    - name: Terraform Validate
      run: |
        cd infra/00-ecr-setup
        terraform validate

    - name: Terraform Plan
      run: |
        cd infra/00-ecr-setup
        terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
        cd infra/00-ecr-setup
        terraform apply -auto-approve tfplan

    - name: List existing ECR repositories
      run: aws ecr describe-repositories
